spring:
  application:
    name: freshco-backend

  # ---------- DATABASE ----------
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  # ---------- JPA ----------
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration-milliseconds: ${JWT_EXPIRATION}

server:
  port: ${SERVER_PORT}

# ---------- SWAGGER ----------
springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: alpha